# ────────────────────────────────────────────────────────────
# Custom Theme for Hyprland
# Made with Omarchist
# ────────────────────────────────────────────────────────────

general {
    col.active_border = rgba(00a86bee) rgba(C3FCB8ee) 45deg 
    col.inactive_border = rgb(00110b)
    border_size = 2
    gaps_in = 3
    gaps_out = 3
}

group {
    col.border_active = rgba(00a86bee)
    col.border_inactive = rgb(00110b)

    groupbar {
        col.active = rgba(00a86b99)
        col.inactive = rgba(3E665088)
        text_color = rgb(D1FFb0)
        text_color_inactive = rgba(e6f6f0ff)
    }
}

decoration {
 rounding = 2
 rounding_power = 3
  shadow {
  enabled = yes
  render_power = 16
  range = 8
  color = rgba(6,11,22, 0.8)
  }
}

