-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(00a86bee)", "rgba(C3FCB8ee)" },
        angle = 45,
      },
      inactive_border = "rgb(00110b)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = "rgba(00a86bee)",
      border_inactive = "rgb(00110b)",
    },
    groupbar = {
      col = {
        active = "rgba(00a86b99)",
        inactive = "rgba(3E665088)",
      },
      text_color = "rgb(D1FFb0)",
      text_color_inactive = "rgba(e6f6f0ff)",
    },
  },
  decoration = {
    rounding = 2,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 16,
      range = 8,
      color = "rgba(6,11,22, 0.8)",
    },
  },
})
