# Undind
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
unbind = SUPER, W
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, T
unbind = SUPER CTRL, C
unbind = SUPER, L
unbind = SUPER, SHIFT, A

bindd = SUPER, Q, Close current window, killactive
bindd = SUPER ALT, K, Show key bindings, exec, omarchy-menu-keybindings
bindd = SUPER ALT, P, Power profile, exec, omarchy-menu power
bindd = SUPER ALT, C, Capture menu, exec, omarchy-menu capture

# Application bindings
bindd = SUPER, T, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, Y, Yazi, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" -e yazi
bindd = SUPER, E, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER CTRL, C, VS Code, exec, uwsm app -- code
bindd = SUPER ALT, T, Activity monitor, exec, omarchy-launch-tui btop
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER, slash, Passwords, exec, uwsm app -- bitwarden-desktop

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# AI Chatbots Menu
bindd = SUPER SHIFT, A, AI Apps, exec, walker -m menus:aiChatbots --width 295 --minheight 1 --maxheight 630
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-webapp "https://discord.com/channels/@me"
#bindd = SUPER SHIFT, C, Claude, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER CTRL, G, GitHub, exec, omarchy-launch-webapp "https://github.com"
#bindd = SUPER SHIFT, G, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"

# Window Actions
bindd = SUPER ALT, J, Toggle split, layoutmsg, togglesplit
bindd = SUPER SHIFT, T, Toggle floating, togglefloating,

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
bindd = SUPER SHIFT, h, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, l, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, k, Swap window up, swapwindow, u
bindd = SUPER SHIFT, j, Swap window down, swapwindow, d

bindd = SUPER CTRL SHIFT, L, Resize to the right, resizeactive, 45 0
bindd = SUPER CTRL SHIFT, H, Resize to the left, resizeactive, -45 0
bindd = SUPER CTRL SHIFT, K, Resize upwards, resizeactive, 0 -45
bindd = SUPER CTRL SHIFT, J, Resize downwards, resizeactive, 0 45

# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
