# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,16
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,16



# NVIDIA (Maxwell/Pascal/Volta without GSP firmware)
env = NVD_BACKEND,egl
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
