### Windowrules ###

# Global opacity — all windows
windowrule = opacity 0.8 override 0.7 override, match:class .*

# Disable opacity exceptions
windowrule = opacity 1.0 override 1.0 override, match:class ^(virt-manager)$
windowrule = opacity 1.0 override 1.0 override, match:class brave-browser
windowrule = opacity 1.0 override 1.0 override, match:class ^brave-.*__-Default$

# Steam
windowrule = opacity 1.0 override 1.0 override, match:class steam
windowrule = tile on, match:class steam
windowrule = center on, match:class steam, match:title Steam
windowrule = size 1920 1080, match:class steam, match:title Steam
windowrule = size 460 800, match:class steam, match:title Friends List
