# Last Call — hand-authored Solarized-influenced palette

[colors-dark]
alpha=0.85
blur=yes
foreground=94b3b5
background=0b1d20
selection-foreground=c8e3e2
selection-background=42686f
cursor=0b1d20 e0f5f2

regular0=0b1d20
regular1=ed634c
regular2=58ad73
regular3=b79a54
regular4=668ca9
regular5=9c8499
regular6=00c6c2
regular7=94b3b5

bright0=42686f
bright1=f47a64
bright2=8fa99a
bright3=b5b49b
bright4=899fa4
bright5=a4939e
bright6=a9c2c1
bright7=e0f5f2
