# Last Call — hand-authored Solarized-influenced palette

background = #0b1d20
foreground = #94b3b5
background-opacity = 0.85

selection-background = #42686f
selection-foreground = #c8e3e2
cursor-color = #e0f5f2
cursor-text = #0b1d20

palette = 0=#0b1d20
palette = 1=#ed634c
palette = 2=#58ad73
palette = 3=#b79a54
palette = 4=#668ca9
palette = 5=#9c8499
palette = 6=#00c6c2
palette = 7=#94b3b5
palette = 8=#42686f
palette = 9=#f47a64
palette = 10=#8fa99a
palette = 11=#b5b49b
palette = 12=#899fa4
palette = 13=#a4939e
palette = 14=#a9c2c1
palette = 15=#e0f5f2
